services:
  backend:
   build: ./backend
   image: bringer_backend
   container_name: bringer_be
   environment:
     BE_PORT: 5000
     FE_PORT: 9040
     CONFIG: dev
     DB_URI: ./data/users.db
   networks: 
     - backend
   ports:
    - 9030:5000
  frontend:
   build: ./frontend
   image: bringer_frontend
   container_name: bringer_fe 
   environment:
     REACT_APP_BE_PORT: 9030
   networks: 
     - frontend
     - backend
   ports:
    - 9040:3000
   depends_on:
     - backend
  
networks:
  backend:
  frontend: